### ISSUE TITLE
run  overrules standard java debug/run tests

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang-idea#1]
after installing jbang all my normal java runs are overruled. i.e. when trying to run junit test method it runs it as a jbang instead of normal java. 

should not overrule normal java actions IMO. should be an option.

**Comment by maxandersen** [comment]
ah - issue is that https://github.com/jbangdev/jbang-idea/blob/1dc95f5cd90e2f5e9c975b1047d63fb8861991c4/src/main/kotlin/dev/jbang/intellij/plugins/jbang/run/JbangRunConfigurationProducer.kt#L31 assumes "//DEPS" can occur anywhere - it should only be if on beginning of a line. regexp match "^//DEPS.*"

**Comment by linux-china** [comment]
How about following code?   

```java
  if (!(code.contains("///usr/bin/env jbang")
                    || code.startsWith("//DEPS ")
                    || code.contains("\n//DEPS "))) return false
```

Regex is not performance well for long text.

**Comment by maxandersen** [comment]
I don't think regex of the type just checking start of line is much slower than checking a string contains something. 

But anyhow - thinking about this we don't really want the existing ones for java to disappear as it's still very feasible to run/debug the file directly. 

Can we just add to list of existing one (run,debug, etc) without removing them ?

**Comment by linux-china** [comment]
Yes, you can.  Now run by JBang is the first option, and you can run it as Normal Java class from `More Run/Debug`.   You should right click outside of class.  It's some tricky and maybe it's bug of IntelliJ IDEA.  I will submit an issue to check.

<img width="1129" alt="Screen Shot 2021-12-24 at 12 34 03 AM" src="https://user-images.githubusercontent.com/46711/147335102-20863c55-ea8e-4509-823c-ab529280b3a0.png">

**Comment by maxandersen** [comment]
no way to make jbang show up in more run/debug instead of "overtaking" the UI ?

**Comment by linux-china** [comment]
Another options is to use external tools in IDEA. External tool will not modify anything to `Run Configurations` and nothing changed to editor popup menu.  Just add JBang under `External Tools`, and of course you can assign shortcut for it.

<img width="955" alt="Screen Shot 2021-12-25 at 7 01 47 PM" src="https://user-images.githubusercontent.com/46711/147397887-5258eaea-4308-4e51-9d98-96208e76496f.png">

**Comment by linux-china** [comment]
One more options:  if right click in JBang directives, and JBang will be first run option,  and native run configuration will be first in other location.

**Comment by linux-china** [comment]
@maxandersen  How about new implementation?

Right Click in JBang directives area, then you can choose `Run Hello.java by JBang`:  

<img width="678" alt="Screen Shot 2021-12-29 at 7 26 39 PM" src="https://user-images.githubusercontent.com/46711/147719358-4a49aeb6-a686-4e2c-9a9c-75257ff37caf.png">

In other area,  `Run by JBang` will be disabled and only run normal Java class available. 

<img width="694" alt="Screen Shot 2021-12-29 at 7 26 57 PM" src="https://user-images.githubusercontent.com/46711/147719363-bf9de175-7ee4-40fb-bcba-1c98c39d6c1f.png">


Line marker will add jbang icon to run script when  `///usr/bin/env jbang `   available in script file. 

```xml
        <runLineMarkerContributor language="JAVA" implementationClass="dev.jbang.idea.run.JBangRunLineMarkerContributor"/>

```

**Comment by maxandersen** [comment]
I think that makes sense as it's more the file you run than the class. 

Maybe also recognize //DEPS and //JAVA in beginning of line as the /// marker is not a hard requirement?

**Comment by linux-china** [comment]
line marker adjusted:

* icon for `///usr/bin/env jbang ` if available
* Icon for `//JAVA` if `///usr/bin/env jbang ` absent
* Icon for first `//DEPS ` if `///usr/bin/env jbang ` and `//JAVA`  absent
