### ISSUE TITLE
Code completion does not work with native edit

### ISSUE THREAD

**Issue by hlavki** [jbangdev/jbang-idea#101]
Hi,

I am using Intellij Idea Ultimate (2023.3.2) with Jbang plugin (0.24.4) and jbang (0.114.0). When I do this steps:

```bash
jbang init -t cli dkman.java
jbang edit --open=idea dkman.java
```

 IDE opens the project, but code completion provides classes only from JDK, not from dependencies (picocli, etc).
It works if I use `-b` option in edit.

**Comment by maxandersen** [comment]
Does Right click in the source file editor give a synchronize jbang option?

**Comment by hlavki** [comment]
@maxandersen yes, it gives me that option. When I run it I get:
![image](https://github.com/jbangdev/jbang-idea/assets/5858133/1bb53692-32b5-404b-9e0b-f349154daeda)

But classes from //DEPS dependencies are not suggested for completion.

**Comment by maxandersen** [comment]
IntelliJ requires the file is in a directory marked as sources. You can right click it's parent and add as sources. 

Let's see if it's that.

**Comment by hlavki** [comment]
thanks @maxandersen, it works now.

**Comment by maxandersen** [comment]
Cool. Thanks to confirm. 

Really should find a way to inform users or even better have it "just work"
