### ISSUE TITLE
use jbang templates catalogs instead of plugin custom templates

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang-idea#14]
I see more and more templates added to this plugin - that undermines the whole notion of jbang templates and catalogs.

We should remove the idea specific templates and use jbang already existing templates and catalogs mechanism that is made to support these things.

**Comment by linux-china** [comment]
Now `JBang Script` uses JBang templates now.   Developers can create their file templates for JBang in IDEA if they would like to do.

**Comment by maxandersen** [comment]
https://github.com/jbangdev/jbang-idea/tree/main/src/main/resources/fileTemplates/internal still has templates present that we can't/should maintain.

**Comment by linux-china** [comment]
Clean done.
