### ISSUE TITLE
IDEA Freezes on Sync 

### ISSUE THREAD

**Issue by nandorholozsnyak** [jbangdev/jbang-idea#19]
I really like the JBang IDEA plugin, but sometimes it literally just kills IDEA. On Windows I experience this bug more than on Linux (Pop OS).  I would say I experience these issues when the script is having a lot of dependencies or all the dependencies are not on the system so it should be downloaded.

Is there any way to make it somehow async like the indexing in IDEA, it is just a progress bar in the bottom?

I have no proper reproduction steps for it, but I think it is the same for other users as well when Sync is happening.

**Comment by linux-china** [comment]
Yes,  it's a known problem,  especially lots of dependencies and dependencies not in your local maven repository.  Now the plugin calls `jbang info tools Hello.java` command line(ProgressBuilder)  to get dependencies  information, and I will fix it later.

**Comment by nandorholozsnyak** [comment]
Cool, thank you!

**Comment by linux-china** [comment]
Fixed with 0.16.0
