### ISSUE TITLE
Add groovy library for JBang Groovy Script automatically

### ISSUE THREAD

**Issue by linux-china** [jbangdev/jbang-idea#2]
Now if you create JBang groovy script, and IDEA will ask you to create Groovy library to Groovy Script.    

Adjusting: 

*  check groovy library available during JBang groovy script creation
* if no groovy library found, create default groovy library for Groovy script

Issues:
* How to change Groovy library version if Groovy script uses new version with `//GROOVY 4.0.0`
* Different Groovy scripts use different groovy version, how to deal with global groovy library?  -- Ask developer to use same Groovy version in same project?

**Comment by maxandersen** [comment]
this is not something a ide plugin shoould do. how do I repdocue this issue of intellji complaining about creating groovy library?

**Comment by linux-china** [comment]
This feature is not necessary because dependencies synced between JBang and Gradle  ready now.

**Comment by maxandersen** [comment]
How does it solve that?

**Comment by linux-china** [comment]
After developer clicks `Sync Dependencies` for Groovy script, and the action will add `org.codehaus.groovy:groovy:version` to build.gradle,  then reload Gradle and groovy library will be available.

**Comment by maxandersen** [comment]
Why are those dependencies not in the build.gradle to begin with ? Is jbang edit not putting it there or ?

**Comment by linux-china** [comment]
Yes,   if  `jbang edit --open=idea hello.groovy`  adds `org.codehaus.groovy:groovy:version`  in build.gradle, and it will be good.

**Comment by maxandersen** [comment]
No. Jbang exit Wont add it. Did You mean jbang init ?

**Comment by linux-china** [comment]
Now the developers just right click the groovy script and choose `Sync DEPS to Gradle` and plugin will sync groovy artifact to Gradle then Groovy library will be created from Gradle. 

![Screen Shot 2021-12-28 at 6 55 51 PM](https://user-images.githubusercontent.com/46711/147623202-73f730ba-48b1-46e9-98c9-d7f24a5aa8a6.png)

**Comment by maxandersen** [comment]
Eh? Sync deps will add dependencies that does not exist ? I assume you mean it will sync it if they are present in the file ?

**Comment by linux-china** [comment]
The plugin can detect that no DEPS related with Groovy script and no groovy related dependencies for module, we have some ways to help developers: 

* warning:  you should add `org.codehaus.groovy:groovy:3.0.9`  by hand
* add `//DEPS org.codehaus.groovy:groovy:3.0.9` to code automatically

In IDEA Inspection almost with a quick fix, and what's your suggestion?

**Comment by maxandersen** [comment]
I think its fine to provide quick fixes/warnings that are helpful.

Adding dependencies automagically into the dependencies when run inside IntelliJ *differently* from how jbang would run it would be a big no-no. We should ensure things runs in a consistent same way.

If the sync adds dependencies which then at least are in the script file the behaviors will at least be the same when running - but if its something actually missing in the dependencies it feels more like a quick fix.

I'll try the latest main version to see how it works but by default I'll assume any "magic" dependency add/remote in the plugin signals of a problem that should be fixed properly somewhere else. I.e. if jbang idea just use jbang tools classpath to setup the module info in IDEA then there should be be no need for the plugin to do anything here, right?
