### ISSUE TITLE
get credentials moved to jbangdev so we can automate publish

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang-idea#20]
we should get jbang plugin permissions assigned to jbangdev org and setup publishing and announcement similar to everything else.

@linux-china did you get message back from intellij ?

**Comment by linux-china** [comment]
@maxandersen  confirm the  account name, is it `jbangdev`, right?   I'm in jetbrains plugin slack group, and I will communicate with Natalia Melnikova.  I think she can help us to transfer the plugin.

**Comment by maxandersen** [comment]
yes, you are member of it at https://plugins.jetbrains.com/organizations/jbangdev

as I understand it you should be able to just edit/move the plugin to it.

**Comment by linux-china** [comment]
Communication with Natalia Melnikova already, and waiting for her feedback.

**Comment by linux-china** [comment]
@maxandersen  Transfered to jbangdev account, please check.

**Comment by maxandersen** [comment]
I see it! Great! Thanks. 

next to get keys etc. setup for publish on tag/release build. I'll try take a look later today.

**Comment by maxandersen** [comment]
this is now setup  - automatic draft release for commits to main and when release ready just release draft release.

no human intervention necessary.

**Comment by linux-china** [comment]
@maxandersen 

How about release on tags?

```
on:
  push:
    tags:
      - '*'
```
