### ISSUE TITLE
builds been failing since 0.9

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang-idea#23]
all pr builds and ci builds https://github.com/jbangdev/jbang-idea/actions are failing as not releasing using the approach outlined in the plugin template. 

MEaning impossible to submit pull requests and know if tests  passes and the release setup is non-reproducible.

lets please fix this and stop doing it manually which only one person can do.

**Comment by linux-china** [comment]
Fixed. Suppress the MISSING_DEPENDENCIES now.
