### ISSUE TITLE
//DEPS content assist not working unless I do content assist in a build.gradle first

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang-idea#26]
I cannot get  //DEPS to content assist unless I have used content assist in build.gradle or pom.xml first.

As if index search not fully enabled without it ?

**Comment by linux-china** [comment]
repository-search plugin is independent  https://github.com/JetBrains/intellij-community/blob/master/plugins/repository-search/src/main/resources/META-INF/plugin.xml  

It can work with none maven/gradle projects, and it works well with normal idea project.  

<img width="1235" alt="Screen Shot 2022-01-23 at 2 17 46 PM" src="https://user-images.githubusercontent.com/46711/150700193-bf1ebe7c-c407-44e6-8b7b-92a51871d8e8.png">

**Comment by maxandersen** [comment]
What does that mean ? That it works for you? 

It doesn't for me. There is no content assist to start Afaics.

**Comment by maxandersen** [comment]
figured out what is/was wrong. I assumed the content assist would show up automatically - it only happens when expliclty doing basic autocomplete using alt+space.
