### ISSUE TITLE
//DEPS content assist should include version

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang-idea#27]
default code completion is not including version meaning it will fail (unless you have a @pom import that manages it).

any reason why the default content assist don't add latest version ?

i.e. instead of:
```
//DEPS com.android.support:appcompat-v7
```
you get 
```
//DEPS com.android.support:appcompat-v7:28.0.0-rc02
```

**Comment by linux-china** [comment]
Yes, it could.   I added version for code completion.

```
                  val lookupString = if (searchVersion) {
                            item.version.toString()
                        } else {
                            if (item.version != null) {
                                "${item.key}:${item.version}"
                            } else {
                                item.key
                            }
                        }
```

screenshot: 

<img width="737" alt="Screen Shot 2022-01-23 at 2 40 19 PM" src="https://user-images.githubusercontent.com/46711/150700912-4ed59148-29af-4009-aa70-426c519ac72e.png">
