### ISSUE TITLE
jbang module dependencies ends up on test classpath when file is named Test.java

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang-idea#42]
not sure why but if I create a file called myTest.java the dependencies gets added to a "jbangTest" classpath even though the file is in the main source folder causing it to not compile.

**Comment by nandorholozsnyak** [comment]
Because of this:
https://github.com/jbangdev/jbang-idea/blob/main/src/main/kotlin/dev/jbang/idea/actions/SyncDependenciesAction.kt#L337

And this
https://github.com/jbangdev/jbang-idea/blob/main/src/main/kotlin/dev/jbang/idea/actions/SyncDependenciesAction.kt#L352

**Comment by maxandersen** [comment]
Yeah that's just wrong. :)
