### ISSUE TITLE
Java version not being synced within module

### ISSUE THREAD

**Issue by nandorholozsnyak** [jbangdev/jbang-idea#44]
If the `//JAVA` directive is given in the JBang script and sync action will not update the Language level in the specific module.

![image](https://user-images.githubusercontent.com/11406183/158188806-f9531f8a-193d-48cd-bd3d-746b7c55d103.png)
![image](https://user-images.githubusercontent.com/11406183/158188838-c7855c72-134d-4f62-8491-9cdbc784a245.png)

**Comment by nandorholozsnyak** [comment]
Sorry, it works, only the SDKs should be named after the Java version. Maybe out could be enhanced with a smarter resolution strategy. I have different Java versions from different vendors (temurin, coretto).

**Comment by linux-china** [comment]
Closed by 0.18.0
