### ISSUE TITLE
External library name is always jbang

### ISSUE THREAD

**Issue by nandorholozsnyak** [jbangdev/jbang-idea#45]
After the jbang script is being syncronized it has the name `jbang` for the dependency collector thing, but if a multi module project is being used it could be a bit "annoying", is there any way to append the name of the module as a prefix for the dependency collector?

Original:
![image](https://user-images.githubusercontent.com/11406183/158190076-b8914c20-f4dd-4356-8e46-c12cb4079414.png)

Idea:
![image](https://user-images.githubusercontent.com/11406183/158190126-3ea37199-4d31-4760-82e5-4ffa68ef6020.png)

**Comment by maxandersen** [comment]
would it not be more right to name it after the root file the classpath library was made?

**Comment by nandorholozsnyak** [comment]
> would it not be more right to name it after the root file the classpath library was made?

So you say if it has three files for example, App.java, AnotherApp.java and forexmaple TestApp.java, then should it be called App-jbang? It can work yeah, but what about the AnotherApp.java or maybe it could be named after the folder that contains all the files.

For me the module's name make sense to use, but I can imagine that it could/should be configurable. One module/folder can have multiple JBang scripts (depends on the use cases of course), so with that in my how would you infer that name?

**Comment by linux-china** [comment]
Closed by 0.18.0

**Comment by maxandersen** [comment]
Fixed how @linux-china ?

**Comment by maxandersen** [comment]
Ah it was done some weeks ago. Was looking for recent PRs and couldn't find jt :)

Still thinks this should be named per source file rather than per module but current behavior works for now.
