### ISSUE TITLE
Support invoking catalogs in the Run configuration

### ISSUE THREAD

**Issue by gastaldi** [jbangdev/jbang-idea#57]
When choosing which script to run, it should be possible to specify a catalog in a remote repository, akin to `jbang run catalog_publish@quarkusio`

![Screen-Shot-2022-04-28-at-21 45 30](https://user-images.githubusercontent.com/54133/166699882-997d35b5-7ceb-4d72-9cfc-eea410f43bcd.png)

**Comment by linux-china** [comment]
@gastaldi  I can implement this feature, but I'm not sure that it's good solution or not. If you want to invoke remote catalog, and it's better to choose a command runner.  Now I use https://github.com/casey/just  and it's very simple. 

```
# publish catalog
catalog_publish:
  jbang run catalog_publish@quarkusio

```

**Comment by gastaldi** [comment]
@linux-china thanks for the links. I'm afraid your solution doesn't seem so different from what JBang already offers, so I am not sure introducing a command runner would help here.

IMHO supporting catalogs in the JBang Run configuration is a more straightforward solution and would be really useful (at least for me :)).

**Comment by linux-china** [comment]
@gastaldi Got. It's not hard and I have fixed it already.  Please install the attachment manually to try it.  If nothing wrong, and I will release a new version next week. 

[jbang-idea-plugin-0.19.0.zip](https://github.com/jbangdev/jbang-idea/files/8647939/jbang-idea-plugin-0.19.0.zip)

**Comment by gastaldi** [comment]
LGTM, it works! I think the "Script File" label might need to be renamed to something that says that you can use a catalog there?
