### ISSUE TITLE
Possibly invalid reference to 'NotUnderContentRootModuleInfo.project'

### ISSUE THREAD

**Issue by yanex** [jbangdev/jbang-idea#60]
Hello! I am a maintainer of the Kotlin IntelliJ IDEA plugin.
During the plugin refactoring, I found out that the JBang plugin uses the `NotUnderContentRootModuleInfo.project` method.

Here is the exact call site:
https://github.com/jbangdev/jbang-idea/blob/af96dbaf65d1fdf5a3c23f81e8f39b725dfdc5a0/src/main/kotlin/dev/jbang/idea/actions/CreateFromTemplateAction.kt#L71

I suppose using `NotUnderContentRootModuleInfo.project` there is unexpected, as the method always returns `null`.
It would be great if you review this code fragment.

**Comment by linux-china** [comment]
@yanex  thanks for your remind.  `NotUnderContentRootModuleInfo.project` was introduced by auto import, and I have fixed it already.
