### ISSUE TITLE
sync to gradle causes duplication of dependencies if deps not found

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang-idea#7]
I had this in my jbang file:

``
//DEPS info.picocli:picocli:4.5.0
```

changed it to:

```
//DEPS info.picocli:picocli:4.5.7
```

ran sync, and now I have:

```
//DEPS info.picocli:picocli:4.5.0
//DEPS info.picocli:picocli:4.5.7
```

and in build.gradle:

```
	implementation 'info.picocli:picocli:4.5.0'
  implementation  'info.picocli:picocli:4.5.7'
```

this should not happen - It should not do destrucive edits.

**Comment by maxandersen** [comment]
actually happens for any kind of edit and no option for  undo.

**Comment by linux-china** [comment]
yes, it's a bug

**Comment by linux-china** [comment]
Dependency logic adjusted to one way:  sync gradle to `//DEPS` or `//DEPS` to gradle.   Version conflict   resolved
