### ISSUE TITLE
sync to gradle does not honor/understand property replacements

### ISSUE THREAD

**Issue by maxandersen** [jbangdev/jbang-idea#8]
Have somethiung like:

```
//DEPS info.picocli:picocli:4.5.0
//DEPS org.jfxtras:jfxtras-icalendaragenda:9.0-r1
//DEPS org.openjfx:javafx-controls:11.0.2:${os.detected.jfxname}
//DEPS org.openjfx:javafx-graphics:11.0.2:${os.detected.jfxname}
```
and jbang idea does not resolve ${os.detected.jfxname} 

I really do not think it is a good idea jbang-idea tries to duplicate jbang's logic.

why not just run jbang edit command and it is synced properly ?
or at least use `jbang info tools` to get the *right* set of dependencies?

**Comment by linux-china** [comment]
Fixed. Now the dependencies resolved by CLI `jbang info tools hello.java`
