### ISSUE TITLE
Bundle jbang.jar into plugin

### ISSUE THREAD

**Issue by linux-china** [jbangdev/jbang-idea#9]
If plugin bundles with jbang.jar and plugin can call JBang functions by API directly,  just like JetBrains Maven plugin, for example dependencies resolve, templates, script creation directly from API, not from command line.   Not sure Jbang can be used as embed mode. 

One issue here:  IDEA's classloader is different with JBang's classloader.     #5

**Comment by maxandersen** [comment]
No. Please do not do This at This stage. Use users installed jbang so users are not locked to whatever version is embedded in their IDE.

**Comment by linux-china** [comment]
jbang.jar bundle removed
