### ISSUE TITLE
Support IDE build 233.x

### ISSUE THREAD

**Issue by nandorholozsnyak** [jbangdev/jbang-idea#97]
Hello there,

New IDEA major version is coming, but the plugin is not yet supporting it.

Can you please release a version that supports the 233.x.x builds?

Thank you.

**Comment by nandorholozsnyak** [comment]
I've just read this page: https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html

> Not specifying until-build means it will include all future builds. This includes future, yet unreleased versions and possibly new IDEs, which might impact compatibility later.

Would it make sense to avoid using that until-build attribute to make sure future releases are supported automatically?

**Comment by linux-china** [comment]
0.24.4 released with IntelliJ IDEA 2023.3 compatible.

**Comment by nandorholozsnyak** [comment]
Thank you so much @linux-china !
